# Configuration registry for LLaMA models
[llama-2-7b]
weights_directory = meta-llama/Llama-2-7b-hf
name = LLaMA-2-7B
probe_layer = 13
noperiod = False

[llama-2-13b]
weights_directory = meta-llama/Llama-2-13b-hf
name = LLaMA-2-13B
probe_layer = 14
intervene_layer = 8
noperiod = False

[llama-2-70b]
weights_directory = meta-llama/Llama-2-70b-hf
name = LLaMA-2-70B
probe_layer = 27
intervene_layer = 8
noperiod = False

[llama-3.1-70b]
weights_directory = meta-llama/Llama-3.1-70B
name = Llama-3.1-70B
probe_layer = 40
noperiod = False

[llama-3.1-70b-instruct]
weights_directory = meta-llama/Llama-3.1-70B-Instruct
name = Llama-3.1-70B-Instruct
probe_layer = 40
noperiod = False
